import './globals.css';
import type { Metadata } from 'next';
import { Sora } from 'next/font/google';
import cn from 'classnames';
import Navbar from '@/components/Navbar';

const sora = Sora({
  weight: ['200', '300', '400', '500', '600', '700', '800'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn('bg-background text-mainColor', sora.className)}>
        <Navbar />

        {children}

        <section className="p-[75px_0_25px] container md:p-[25px_0]">
          <div className="flex flex-col items-center gap-[50px]">
            <div className="linear-rect"></div>
            <div className="text-[14px] font-[500]">Powered by NUAH</div>
          </div>
        </section>
      </body>
    </html>
  );
}
